const API_IP = 'http://localhost:3000';

const TOKEN_NAME = 'token';

const LOGIN_USER = 'LOGIN_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const CHECK_USER_AUTH = 'CHECK_USER_AUTH';

const GET_TODOS = 'GET_TODOS';
const CREATE_TODO = 'CREATE_TODOS';
const UPDATE_TODO = 'UPDATE_TODOS';
const DELETE_TODO = 'DELETE_TODO';

export {
  API_IP, TOKEN_NAME, 
  LOGIN_USER, LOGOUT_USER, 
  CHECK_USER_AUTH, GET_TODOS, 
  CREATE_TODO, UPDATE_TODO, 
  DELETE_TODO
};